In [1]:
import numpy as np

<img src="https://p3.storage.canalblog.com/37/36/99623/47284274.jpg">

In [2]:
grid = np.array([[0,0,2,0,8,0,0,6,3],
                 [0,0,1,3,0,0,0,9,0],
                 [4,0,0,9,6,0,0,0,1],
                 [0,0,0,0,0,0,0,0,0],
                 [0,7,9,8,0,0,0,0,4],
                 [1,0,0,0,3,0,0,0,9],
                 [3,0,8,0,0,0,1,2,7],
                 [0,0,7,2,0,0,0,4,5],
                 [0,0,4,7,0,0,9,0,6]])

In [3]:
print(grid)

[[0 0 2 0 8 0 0 6 3]
 [0 0 1 3 0 0 0 9 0]
 [4 0 0 9 6 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 7 9 8 0 0 0 0 4]
 [1 0 0 0 3 0 0 0 9]
 [3 0 8 0 0 0 1 2 7]
 [0 0 7 2 0 0 0 4 5]
 [0 0 4 7 0 0 9 0 6]]


In [5]:
def possible(x, y, n):
    global grid
    if np.any(grid[x,:] == n):
        return False
    if np.any(grid[:,y] == n):
        return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    if np.any(grid[x0:x0+3,y0:y0+3] == n):
        return False
    return True

In [6]:
def solve_sudoku():
    global grid
    # loop over all points in the gird
    for x in range(9):
        for y in range(9):
            # if we have a blank,  try to fill it
            if grid[x, y] == 0:
                for n in range(1,10):
                    if possible(x, y, n):
                        # if its possible to fill, fill it
                        grid[x, y] = n
                        # recurse
                        solve_sudoku()
                        # back track if not possible to solve
                        grid[x, y] = 0
                # retrun if done
                return
    # show result
    print(grid)

In [7]:
solve_sudoku()

[[9 5 2 1 8 4 7 6 3]
 [7 6 1 3 2 5 4 9 8]
 [4 8 3 9 6 7 2 5 1]
 [8 3 6 4 7 9 5 1 2]
 [2 7 9 8 5 1 6 3 4]
 [1 4 5 6 3 2 8 7 9]
 [3 9 8 5 4 6 1 2 7]
 [6 1 7 2 9 8 3 4 5]
 [5 2 4 7 1 3 9 8 6]]
